pipeline {
    agent any
    tools {
        jdk 'jdk8'
        maven 'maven3'
    }
	
    stages {
		stage('cleanup') {
		    steps {
			    deleteDir()
		    }
		}
		stage('check out source file') {
		    steps {
			    sh "git clone 
http://root:8f43fb24069bcb2dc55a5d04@gitlab.192.168.191.138.xip.io:31080/root/DEMO.git ."
		    }
		}
        stage('install and sonar parallel') {
            steps {
                parallel(
                        install: {
                            sh "JAVA_HOME=/var/jenkins_home/tools/hudson.model.JDK/jdk8/jdk1.8.0_162 && mvn -U clean test 
cobertura:cobertura -Dcobertura.report.format=xml"
                        },
                        sonar: {
                            sh "JAVA_HOME=/var/jenkins_home/tools/hudson.model.JDK/jdk8/jdk1.8.0_162 && mvn sonar:sonar 
-Dsonar.host.url=http://cicd_sonar:9000 -Dsonar.username=admin -Dsonar.password=admin"
                        }
                )
            }
            post {
                always {
                    junit '**/target/*-reports/TEST-*.xml'
                    step([$class: 'CoberturaPublisher', coberturaReportFile: 'target/site/cobertura/coverage.xml'])
                }
            }
        }
        stage('deploy') {
            steps {
                sh "JAVA_HOME=/var/jenkins_home/tools/hudson.model.JDK/jdk8/jdk1.8.0_162 && mvn deploy -DskipTests 
-Dartifactory_url=http://admin:password123@artifactory.192.168.191.138.xip.io:33081/artifactory/example-repo-local"
            }
        }
    }
}
