---
- name: Build & Deploy Artifact to Docker
  hosts: all
  roles:
    - role: '{{playbook_dir}}'
  vars:
    ansible_ssh_private_key_file: /tmp/id_rsa
    ansible_user: cicd_service_account

  tasks:
    - name: Find out playbooks path
      shell: pwd
      register: ppath
    - debug: var=ppath.stdout

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: '{{ppath.stdout}}/Dockerfile'

    - name: Download artifact
      get_url:
        url: "{{artifact_url}}"
        dest: "{{ppath.stdout}}/app.war"


    - name: Build image
      shell: "docker build -t cicd/insecuredemo:latest . -f {{ppath.stdout}}/Dockerfile"

    - name: Start the container
      docker_container:
        name: cicd_InsecureDemo
        image: cicd/insecuredemo:latest
        ports:
          - "8091:8091"
